### ISSUE TITLE
Permission Groups

### ISSUE THREAD

**Issue by JEK0x81D** [va1kio/commander#10]
### Description
Permission groups would solve the problem of multiple layers (or groups) of administrative/moderative users. For example, if you wanted to give some users permission to fly, but not ban, and another group of users permission to fly and ban, there is currently no way to implement this without modifying the source. With permission groups this would be as trivial as adding two new groups and giving them permission to a certain command.  The name of the permission group of users would be shown in the home page instead of just "Administrator", and may be used in other places to view the permission group of that user.

**Implementation**
I would initially suggest this be implemented as a table of groups, with each group containing data such as name and of course permissions. The format would be simple, just the key being the group name and the values being a table of commands (referenced by their command name, or possibly name of its module script?). Specific people or groups can then be given access to a permission group by setting the user(s) who would get the group as the key and the group they get as the value. The star permission would be used to grant every single command. See example below (Settings.lua):
```lua
return {
	...
	["Admins"] = {
		[game.CreatorId] = "Moderator",
		["nana_kon"] = "Owner"
	},
	["Permissions"] = {
		["Moderator"] = {
			"Kick"
		},
		["Admin"] = {
			"Ban",
			"Shutdown",
			"Time ban"
		},
		["Owner"] = {
			"*"
		}
	}
	...
}
```

Please reply with any feedback or suggestions, thanks.

**Comment by va1kio** [comment]
I feel like it should be incorporated with a ruleset system, so we can create rules for Commander. Such as disallowing the usage of .doThisToPlayers()'s "All"/"Others" prefix

**Comment by va1kio** [comment]
Something like this would do:
-> Rulesets
 -> DisallowPrefixes
 -> PermissionGrps

**Comment by va1kio** [comment]
I assume a modular design would be fine

**Comment by matsumooo** [comment]
The command name for the permission should be based on the package's name. So, "Time Ban" should be "TimeBan"

**Comment by JEK0x81D** [comment]
> 
> 
> I feel like it should be incorporated with a ruleset system, so we can create rules for Commander. Such as disallowing the usage of .doThisToPlayers()'s "All"/"Others" prefix

Could you expand on what you mean by prefix?

**Comment by matsumooo** [comment]
I think what she meant is the "all", "others", "random" thing in the package API

**Comment by JEK0x81D** [comment]
> 
> 
> Something like this would do:
> -> Rulesets
> -> DisallowPrefixes
> -> PermissionGrps

@va1kio could you provide an example of this?

**Comment by va1kio** [comment]
![image](https://user-images.githubusercontent.com/40730127/110276508-3579bc00-800e-11eb-9760-10b8c695b3f2.png)

Like this, @JEK0x81D

**Comment by matsumooo** [comment]
> ![image](https://user-images.githubusercontent.com/40730127/110276508-3579bc00-800e-11eb-9760-10b8c695b3f2.png)
> 
> Like this, @JEK0x81D

This is inefficient and is just decreasing the accessibility for users who do not wish to "mess" with the source code. 

What @JEK0x81D suggested is superior to your suggestion, as the permission thing is just below the part where you add new administrators. They can easily reach to permission group settings with that design.

**Comment by JEK0x81D** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/40730127/110276508-3579bc00-800e-11eb-9760-10b8c695b3f2.png)
> 
> Like this, @JEK0x81D

Are the DiablePrefixes global or only for specific users? Could you provide a use case?

**Comment by va1kio** [comment]
Global, if there's a command utilising .doThisToPlayers and it is extremely abusive with it, they can setup a ruleset to disable the "all"/"others" prefix  in order to decrease the possibility of abuse without modifying the code.

**Comment by JEK0x81D** [comment]
> 
> 
> Global, if there's a command utilising .doThisToPlayers and it is extremely abusive with it, they can setup a ruleset to disable the "all"/"others" prefix in order to decrease the possibility of abuse without modifying the code.

Could that possibly be integrated into permission/trust groups? It'd likely be more useful if it different users had different settings, since a moderator may not be trusted however the owner of the game would be.

**Comment by JEK0x81D** [comment]
One problem that is pretty likely to arise is the matter of priority and inheritance. For example, one may want to block the use of "all" for moderators, but allow it for administrators. If every user with a rank greater than 200 in some group got moderator, and every rank greater than 210 got administrator, since there is no logic to "allow" the use of "all" it would be blocked for administrators. I believe that the best and most intuitive solution to this would be to allow each group to have a priority, and allow it to inherit from other groups as to not have repetition. Inheritance would take the permissions of one group, but not the limits such as disallowing prefixes. The highest priority of group of a user would be the group that the user takes on. Simple example:

```lua
return {
	...
	["Permissions"] = {
		["Moderator"] = {
			["Priority"] = 1,
			["DisallowPrefixes"] = {
				"All",
				"Others"
			},
			["Permissions"] = {
				"Kick"
			}
		},
		["Admin"] = {
			["Inherits"] = "Moderator",
			["Priority"] = 2,
			["Permissions"] = {
				"Ban",
				"Shutdown",
				"TimeBan"
			}
		},
		["Owner"] = {
			["Inherits"] = "Admin",
			["Priority"] = 3,
			["Permissions"] = {
				"*"
			}
		}
	}
	...
}
```

Thoughts appreciated.

**Comment by va1kio** [comment]
Sounds good.
