### ISSUE TITLE
Command usage logging

### ISSUE THREAD

**Issue by va1kio** [va1kio/commander#16]
Should be self-explanatory, we need a logging system for command usage that is precise and does not log any false positives.

However, there's one problem. It's how our command is structured and how command works in our system. Which made command logging a bit harder than the usual administration system

What I am thinking is changing the modal event to make it that developers can **not** connect to the event itself, but only :Wait() on it, so basically, we will just do the yield in the API.

With this method, nested function won't appear, and command usage logging should be easier. Though, we need the developers to return a true boolean if the command ran successfully, which isn't really ideal in terms of saving space. Let me know if there's any solution to this, or this is totally fine.

**Comment by jaydensar** [comment]
Maybe instead of returning `true` on success, it could return `false` or throw an error when it fails?

**Comment by va1kio** [comment]
It would be problematic, but anyway. I've implemented the command logging, and it will send a message to the user if the module does not return the true boolean, telling the user that the command may be incompatible with the current system and will not be logged

**Comment by va1kio** [comment]
Not sure is it fine or not, are you able to check the pr2 branch?
