### ISSUE TITLE
Issue with mobile camera and scrolling on pc

### ISSUE THREAD

**Issue by Agoulstic** [va1kio/commander#20]
**Describe the bug**
I've noticed that when I play Roblox on pc I can move around, but I can't seem to scroll in and out at all. I can only zoom in and zoom out using the o and i letter keys on my laptop.

Though on mobile I'm unable to move around at all, I can only jump, nor can I scroll at all. This appears to be a Commander issue as it worked on removal of the module.

**Expected behavior**
On joining the game, pretty self explanatory but, I would think I'd be able to scroll and move around on both platforms with no issue.

**Desktop (please complete the following information):**
 - Google Chrome

**Smartphone (please complete the following information):**
 - iPhone XR
 - iOS 14.1

**Comment by Nicklaus-s** [comment]
No idea if this will help, but you should be able to tap/click your mouse outside of the GUI and be able to move, jump, and zoom freely.

**Comment by va1kio** [comment]
I've actually noticed the issue in the Preview branch yesterday, it was due to the message UI container.

**Comment by va1kio** [comment]
Resolved in Preview branch, an update addressing these issues will be released by probably before this weekend.
