### ISSUE TITLE
Message close button not functioning

### ISSUE THREAD

**Issue by mvvrgan** [va1kio/commander#27]
When I try to close a message or server message with the 'X', it seems to not work.

**Comment by va1kio** [comment]
I am unable to repro the issue you are facing, are you able to explain in more detail?

**Comment by Ivanmatthew** [comment]
> I am unable to repro the issue you are facing, are you able to explain in more detail?

I think what he means is that other guis can obstruct the functionality of the admin panel. Maybe you should move the displayorder of the panel screengui up?

**Comment by matsumooo** [comment]
Solved in 1.2.0
