### ISSUE TITLE
Add a hint command

### ISSUE THREAD

**Issue by ccuser44** [va1kio/commander#32]
The hint command is the same message but is less noticable. It visually is simular to https://developer.roblox.com/en-us/api-reference/class/Hint
The hint command would display the text PLAYERNAME: ENTEREDMESSAGE
When the hint command would be run multiple times they would render below each other like
PLAYERNAME: ENTEREDMESSAGE
PLAYERNAME: ENTEREDMESSAGE
PLAYERNAME: ENTEREDMESSAGE
And they would be seperate GUI objects. (not the same textlabel)

Also they would disappear after 10 seconds.

**Comment by va1kio** [comment]
It is definitely something we really want to create as an alternative to messages but lower priority, but the problem is how the messages are positioned, which disables us from utilising the space in the topbar, while the bottom is an option, we are honestly not really sure about it.

**Comment by ccuser44** [comment]
The hint command exists now. Going to close this as this pull is now useless.
