### ISSUE TITLE
The panel will not show up.

### ISSUE THREAD

**Issue by Ivanmatthew** [va1kio/commander#56]
`Players.Player1.PlayerGui.Panel.Scripts.Library.Components.SeparatedList:33: invalid argument #3 (string expected, got nil)  -  Client - SeparatedList:33
Stack Begin  -  Studio
Script 'Players.Player1.PlayerGui.Panel.Scripts.Library.Components.SeparatedList', Line 33  -  Studio - SeparatedList:33
Script 'Players.Player1.PlayerGui.Panel.Scripts.Library.Constructors.Home', Line 141  -  Studio - Home:141
Script 'Players.Player1.PlayerGui.Panel.Scripts.Library.Constructors.Home', Line 182  -  Studio - Home:182
Script 'Players.Player1.PlayerGui.Panel.Scripts.Core', Line 43 - function setupModules  -  Studio - Core:43
Script 'Players.Player1.PlayerGui.Panel.Scripts.Core', Line 47  -  Studio - Core:47
Stack End  -  Studio`

**Comment by Ivanmatthew** [comment]
Addendum: This error only occurs with the in-studio multiple player testing.

**Comment by va1kio** [comment]
I am unable to repo this issue, as Commander won't work when in a Test Server (inside Studio), but I've pushed a quick patch to address the nil variable issue, so it won't error even if the argument `#3` is a nil variable, will be only replaced with a `0`

**Comment by Ivanmatthew** [comment]
Superb, thanks
