### ISSUE TITLE
Make Message, Hint and ServerMessage be global commands and have them show for all players.

### ISSUE THREAD

**Issue by ccuser44** [va1kio/commander#74]
Most admin commands do this.

**Comment by ccuser44** [comment]
Or are these implemented already?

Also hint should be global

**Comment by ccuser44** [comment]
Wait private messages exist. But anyways Message, SystemMessage and hint should be global.

**Comment by va1kio** [comment]
What do you mean by global and show for all players? Commands are supposed to be for administrators only, not everyone.

**Comment by va1kio** [comment]
I don’t get it, possible to rephrase it and attach with a screenshot/video describing your issue?

**Comment by ccuser44** [comment]
Hard to explain. Made it in #75
