### ISSUE TITLE
Merging preview into main

### ISSUE THREAD

**Issue by va1kio** [va1kio/commander#78]
We all like Git, it's a powerful utility for teams like us that are working on a project. Well, not until when you are encountering a merge conflict. Not only it wastes a lot of time, it forces people to face code that may not be appealing to them.

While in fact those problems rarely happen, it's not in our case, as we separate production-ready versions away from versions with unreleased features and improvements. Which means once we have finished all the updates, we have to face this horrible nightmare, which is the one we've mentioned earlier in this issue.

There's a very easy solution to this however, which is by just merging the preview branch into the main branch, and delete the preview branch so we will start putting changes to the branch immediately. 

As we have rewritten our documentation to address user to download the source code in the releases section but not cloning the entire repository, this will not affect anyone.

Let me know what's your thought on this, thanks!

**Comment by ccuser44** [comment]
Yeah. But may I ask. What is Thymus?

**Comment by va1kio** [comment]
Thymus is a version of Commander with an entire rewrite of the API and packages. We are still not sure whether will it work out, if not, we'll just scrap that thing
