### ISSUE TITLE
Rely on GitHub for credits

### ISSUE THREAD

**Issue by va1kio** [va1kio/commander#8]
Right now, the credits are typed out rather than relying on an external API service, like a database. Which means when we must add a new entry to the credit list, we must push a new update for Commander, just for it.

With relying on GitHub, we can use a JSON for the credits, and the Commander system can fetch the JSON with HttpService:GetAsync() at first-run. Solving the issue mentioned above.

**Comment by ccuser44** [comment]
Yeah sounds good. However it should have an offline backup in commander as well. Also that offline backup should be ported to the module id if it is going to be released.

**Comment by va1kio** [comment]
Done in #69
